// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLJTzY0xO2mrQwdxE8PC2OjATv02L-Hik',
    appId: '1:555511653468:web:ae9cf77ca533a159703299',
    messagingSenderId: '555511653468',
    projectId: 'add-android-app-b658b',
    authDomain: 'add-android-app-b658b.firebaseapp.com',
    storageBucket: 'add-android-app-b658b.firebasestorage.app',
    measurementId: 'G-G5WJKC4JTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhADIDl8hlSrV3y1erAqdCnxxz87nHOks',
    appId: '1:555511653468:android:a212d9f99b17269b703299',
    messagingSenderId: '555511653468',
    projectId: 'add-android-app-b658b',
    storageBucket: 'add-android-app-b658b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVgMOTVzX5x-Zm9HL8M3Dj5Z0DHuO4jzY',
    appId: '1:555511653468:ios:fe0c5f9842949c7d703299',
    messagingSenderId: '555511653468',
    projectId: 'add-android-app-b658b',
    storageBucket: 'add-android-app-b658b.firebasestorage.app',
    iosClientId: '555511653468-5e2jh6rfeshtkpmdcpk6qujkdmfnbp9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.exerciseApp',
  );
}
